# Generated by Django 4.1 on 2022-08-27 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("SoundboxApp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="SoundboxApp.album",
            ),
        ),
        migrations.AlterField(
            model_name="music",
            name="time_length",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=20),
        ),
    ]
