# Generated by Django 4.1 on 2022-09-01 19:42

import SoundboxApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("SoundboxApp", "0002_alter_music_album_alter_music_time_length"),
    ]

    operations = [
        migrations.AlterField(
            model_name="music",
            name="audio_file",
            field=models.FileField(
                upload_to="musics",
                validators=[SoundboxApp.validators.validate_is_audio],
            ),
        ),
    ]
